name: flutter_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  firebase_analytics: ^10.6.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_webrtc: ^0.9.46
  google_sign_in: ^6.1.5
  http: ^1.1.0
  logger: ^2.0.2+1
  sdp_transform: ^0.3.2
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
