firebase:
  credential:
    resource-path: firebase_config.json
spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:postgresql://localhost:49153/multicast
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
socket:
  host: localhost
  port: 8000